/****************************************************************************
** Form interface generated from reading ui file '/home/gregor/mesydaq2/src/mesydaq2mainwindow.ui'
**
** Created: Di Feb 10 09:22:04 2009
**
** WARNING! All changes made in this file will be lost!
****************************************************************************/

#ifndef WIDGET2_H
#define WIDGET2_H

#include <qvariant.h>
#include <qwidget.h>

class QVBoxLayout;
class QHBoxLayout;
class QGridLayout;
class QSpacerItem;
class QFrame;
class QLabel;
class QTabWidget;
class QButtonGroup;
class QRadioButton;
class QCheckBox;
class QSpinBox;
class QPushButton;
class QLineEdit;
class QGroupBox;
class QComboBox;

class mesydaq2mainwindow : public QWidget
{
    Q_OBJECT

public:
    mesydaq2mainwindow( QWidget* parent = 0, const char* name = 0, WFlags fl = 0 );
    ~mesydaq2mainwindow();

    QFrame* mainFrame;
    QFrame* dataFrame;
    QLabel* textLabel1_5_3;
    QLabel* textLabel1_5;
    QLabel* meanText;
    QLabel* sigmaText;
    QTabWidget* tabWidget5_2;
    QWidget* tab;
    QButtonGroup* logGroup;
    QRadioButton* lin;
    QRadioButton* log;
    QCheckBox* specialBox;
    QCheckBox* dispAll;
    QSpinBox* dispMcpd;
    QLabel* textLabel2;
    QPushButton* clearChan;
    QSpinBox* dispChan;
    QPushButton* clearMcpd;
    QLabel* textLabel1_4_2_3_4_2_2_2;
    QSpinBox* dispMpsd;
    QLabel* textLabel1_4_2_3_4_2;
    QLabel* textLabel1_4_2_3_4_2_2;
    QPushButton* clearMpsd;
    QPushButton* clearAll;
    QButtonGroup* buttonGroup10;
    QRadioButton* dispAllAmpl;
    QRadioButton* dispAllPos;
    QWidget* tab_2;
    QCheckBox* useThresh;
    QLineEdit* loLim;
    QLabel* textLabel1_6;
    QLabel* textLabel1_6_2;
    QLineEdit* hiLim;
    QPushButton* applyDispThreshButton;
    QGroupBox* groupBox1;
    QLineEdit* daqStatusLine;
    QCheckBox* acquireFile;
    QPushButton* startStopButton;
    QPushButton* allPulsersoffButton;
    QLabel* pulserWarning;
    QTabWidget* tabWidget2;
    QWidget* tab_3;
    QLabel* versionLabel;
    QGroupBox* groupBox17;
    QLabel* textLabel1_3_6;
    QLabel* textLabel1_3;
    QLabel* textLabel1_3_3;
    QLabel* textLabel1_3_4;
    QLabel* textLabel1_3_5;
    QLabel* param0;
    QLabel* param1;
    QLabel* param3;
    QSpinBox* paramId;
    QLabel* param2;
    QLabel* hTimeText;
    QLabel* textLabel1_2_3_2;
    QTabWidget* tabWidget11;
    QWidget* tab_4;
    QLabel* textLabel1_11_2;
    QLabel* textLabel1_10_2_2;
    QLabel* monRate2;
    QLabel* monitor2;
    QLabel* mTimeText;
    QLabel* totalCounts;
    QLabel* eventRate;
    QLabel* textLabel1;
    QLabel* textLabel1_10;
    QLabel* tSecsText;
    QPushButton* tPresetButton;
    QPushButton* ePresetButton;
    QPushButton* m2PresetButton;
    QSpinBox* tPreset;
    QLabel* textLabel1_2_3_2_3_2;
    QLabel* textLabel1_2_3_2_3;
    QSpinBox* evPreset;
    QSpinBox* m2Preset;
    QLabel* monitor1;
    QLabel* textLabel1_11;
    QLabel* monRate1;
    QPushButton* m1PresetButton;
    QSpinBox* m1Preset;
    QLabel* textLabel1_10_2;
    QPushButton* tResetButton;
    QPushButton* eResetButton;
    QPushButton* m1ResetButton;
    QPushButton* m2RresetButton;
    QWidget* tab_5;
    QLabel* textLabel1_2_3;
    QLabel* textLabel1_2;
    QLabel* cmdTx;
    QLabel* cmdRx;
    QLabel* textLabel1_2_2;
    QLabel* dataRx;
    QWidget* TabPage;
    QLabel* textLabel1_12;
    QLabel* textLabel1_12_2;
    QLabel* textLabel1_12_2_2;
    QLabel* caressHeight;
    QLabel* caressWidth;
    QLabel* caressRun;
    QWidget* tab_6;
    QLabel* textLabel1_5_2;
    QGroupBox* groupBox30;
    QCheckBox* master;
    QCheckBox* terminate;
    QPushButton* resetTimer;
    QSpinBox* mcpdId;
    QTabWidget* tabWidget5;
    QWidget* tab_7;
    QGroupBox* groupBox9;
    QLabel* textLabel1_7;
    QLabel* textLabel1_7_3;
    QLabel* textLabel1_7_2;
    QPushButton* sendCellButton;
    QComboBox* cellSource;
    QComboBox* cellTrigger;
    QSpinBox* cellCompare;
    QGroupBox* groupBox9_2;
    QLabel* textLabel1_7_4;
    QLabel* textLabel1_7_3_2;
    QPushButton* sendAux;
    QSpinBox* timer;
    QLineEdit* compareAux;
    QGroupBox* groupBox9_2_2;
    QLabel* textLabel1_7_4_2_2;
    QLabel* textLabel1_7_4_2;
    QPushButton* sendParam;
    QComboBox* paramSource;
    QSpinBox* param;
    QGroupBox* groupBox16;
    QCheckBox* statusStream;
    QPushButton* setStream;
    QWidget* tab_8;
    QGroupBox* groupBox29;
    QSpinBox* deviceId;
    QPushButton* setID;
    QGroupBox* groupBox6;
    QLabel* textLabel1_3_2;
    QLabel* textLabel1_3_2_2;
    QLabel* textLabel1_3_2_2_2;
    QCheckBox* dataThisPc;
    QCheckBox* cmdThisPc;
    QCheckBox* modifyIp;
    QLineEdit* mcpdIpAddress0;
    QLineEdit* dataIpAddress0;
    QLineEdit* dataIpAddress2;
    QLineEdit* mcpdIpAddress1;
    QLineEdit* dataIpAddress1;
    QLabel* textLabel1_3_3_2_2;
    QLineEdit* mcpdIpAddress3;
    QLineEdit* mcpdIpAddress2;
    QLineEdit* cmdIpAddress3;
    QLineEdit* dataIpAddress3;
    QLineEdit* cmdIpAddress2;
    QLineEdit* cmdIpAddress1;
    QLineEdit* cmdIpAddress0;
    QLabel* textLabel1_3_3_2;
    QSpinBox* dataUdpPort;
    QSpinBox* cmdUdpPort;
    QPushButton* setIP;
    QWidget* TabPage_2;
    QTabWidget* tabWidget4;
    QWidget* tab_9;
    QSpinBox* devid_2;
    QLabel* textLabel1_4_2_4;
    QGroupBox* groupBox17_2;
    QLabel* textLabel1_4;
    QLabel* textLabel1_4_10;
    QLabel* textLabel1_4_9;
    QLabel* textLabel1_4_8;
    QLabel* textLabel1_4_7;
    QLabel* textLabel1_4_6;
    QLabel* textLabel1_4_5;
    QLabel* textLabel1_4_4;
    QLabel* status3;
    QLabel* status2;
    QLabel* status1;
    QLabel* status4;
    QLabel* status5;
    QLabel* status6;
    QLabel* status7;
    QPushButton* scanPeri;
    QLabel* status0;
    QGroupBox* groupBox39;
    QPushButton* readRegisterButton;
    QSpinBox* registerSelect;
    QLineEdit* registerValue;
    QPushButton* writeRegisterButton;
    QWidget* tab_10;
    QLabel* textLabel1_4_2_2;
    QGroupBox* groupBox13;
    QLabel* textLabel1_4_2_3_2;
    QLabel* textLabel1_4_2_3_3;
    QPushButton* setThreshold;
    QLabel* textLabel1_4_2_3;
    QLineEdit* gain;
    QLabel* textLabel1_4_2_3_3_3;
    QLineEdit* threshold;
    QPushButton* setGain;
    QLabel* textLabel1_4_2_3_3_2;
    QCheckBox* comgain;
    QSpinBox* channel;
    QLabel* textLabel1_4_2;
    QButtonGroup* modeGroup;
    QRadioButton* pos;
    QRadioButton* amp;
    QGroupBox* groupBox35;
    QLabel* textLabel1_4_2_3_4;
    QButtonGroup* buttonGroup4;
    QRadioButton* pulsLeft;
    QRadioButton* pulsMid;
    QRadioButton* pulsRight;
    QButtonGroup* buttonGroup5;
    QLineEdit* pulsAmp2;
    QRadioButton* pulsampRadio1;
    QRadioButton* pulsampRadio2;
    QLineEdit* pulsAmp1;
    QSpinBox* pulsChan;
    QPushButton* pulserButton;
    QSpinBox* module;
    QSpinBox* devid;
    QWidget* TabPage_3;
    QGroupBox* groupBox15;
    QSpinBox* runId;
    QCheckBox* runIdAuto;
    QPushButton* runIdButton;
    QGroupBox* groupBox20;
    QSpinBox* timingBox;
    QLabel* textLabel1_8;
    QWidget* TabPage_4;
    QGroupBox* groupBox79_2;
    QPushButton* saveSetupButton;
    QPushButton* restoreSetupButton;
    QLabel* textLabel2_2;
    QLabel* configfilename;
    QGroupBox* groupBox35_2;
    QLabel* textLabel1_9_3;
    QLabel* textLabel1_9_2;
    QLabel* textLabel1_9;
    QLineEdit* listfilepath;
    QLineEdit* histfilepath;
    QLineEdit* configfilepath;
    QPushButton* selectListpath;
    QPushButton* selectConfigpath;
    QPushButton* selectHistpath;
    QGroupBox* groupBox79;
    QCheckBox* acqListfile;
    QPushButton* replayButton;
    QLineEdit* listFilename;
    QPushButton* selectButton;
    QGroupBox* groupBox36;
    QLabel* textLabel2_2_2;
    QLabel* histfilename;
    QPushButton* writeHistButton;
    QPushButton* LoadhistButton;

public slots:
    virtual void startStopSlot();
    virtual void sendCellSlot();
    virtual void sendParamSlot();
    virtual void sendAuxSlot();
    virtual void resetTimerSlot();
    virtual void setTimingSlot();
    virtual void setMcpdIdSlot();
    virtual void setIpUdpSlot();
    virtual void setPulserSlot();
    virtual void setGainSlot();
    virtual void setThresholdSlot();
    virtual void allPulserSlot();
    virtual void selectListfileSlot();
    virtual void acqListfileSlot();
    virtual void setStreamSlot();
    virtual void clearAllSlot();
    virtual void clearMcpdSlot();
    virtual void clearMpsdSlot();
    virtual void clearChanSlot();
    virtual void replayListfileSlot();
    virtual void setRunIdSlot();
    virtual void displayMcpdSlot(void);
    virtual void displayMpsdSlot(void);
    virtual void scanPeriSlot();
    virtual void setModeSlot(int);
    virtual void saveSetupSlot();
    virtual void restoreSetupSlot();
    virtual void saveConfigSlot();
    virtual void redrawSlot();
    virtual void applyThreshSlot();
    virtual void linlogSlot();
    virtual void writeRegisterSlot();
    virtual void readRegisterSlot();
    virtual void selectListpathSlot();
    virtual void selectHistpathSlot();
    virtual void selectConfigpathSlot();
    virtual void writeHistSlot();
    virtual void ePresetSlot(bool);
    virtual void tPresetSlot(bool);
    virtual void m1PresetSlot(bool pre);
    virtual void m2PresetSlot(bool);
    virtual void tResetSlot();
    virtual void eResetSlot();
    virtual void m1ResetSlot();
    virtual void m2ResetSlot();

protected:

protected slots:
    virtual void languageChange();

};

#endif // WIDGET2_H
